twig:
    file_name_pattern: '*.twig'
    
    # Configuration pour appeler RequestRepository dans la navbar
    globals:
        RequestRepository: '@App\Repository\RequestRepository'


when@test:
    twig:
        strict_variables: true
